sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
branches:
  only:
    - master
before_install:
  - npm install
after_success:
  - npm run semantic-release
