language: node_js
node_js: '10'
cache: yarn
env: 
  #- CXX=g++-4.9
  - NPM_TOKEN=0b1bd709-e1fc-49b6-8bc6-d12a4fa2bf86
notifications:
  email: false
addons:
  apt:
    sources: 
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - g++-4.9
      - libcairo2-dev
      - libpango1.0-dev
      - libssl-dev
      - libjpeg62-dev
      - libgif-dev
      - pkg-config
after_success:
  - yarn travis-deploy-once "yarn semantic-release"
