sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
branches:
  only:
    - master
before_install:
  - npm install -g npm@^2.0.0
  - npm install
before_script:
  - npm prune
after_success:
  - npm run semantic-release
