language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
branches:
  only:
    - master
install:
  - travis_retry npm install
after_success:
  - npm run semantic-release
